language: go

go:
  - "1.10.x"
  - "1.9.x"
  - "1.8.x"
  - master

env:
  global:
    - secure: "F1MWBFOxaa1vcb0bnjVTuVEzzaqxQykwHVzdeevKGG6qGwBqDoKjzDym1XbWdZkfsu6N2sEz6Xo9wAMQwc1nhBJTufQOKjwqy0zDXsKMF5aouvswqe4eEZ95IU8Ww30jGiw1E4d6RfvTvYOwZszB+vIvqJ7gs8msFr0wJaQUpJk+Qpd5TtNb8poY7J0qQH0GevlNIY5SieM52BbQKodEC9aUUTFYOvoZEOAiLPX/6qS1hvfOIwHEFxXo9jrUSiSyqYZTfEN9CExsO3M5iJQz1ZVvtylXpATcZ6Imo3Q5eL288wTx4VUjL/lrnS1vIkmgG0HWyOYg4FGl9l4TsANGf3EnByBtZmFJ/MLjmqtWQzodvU2wMCseVJ/MQzi6iOkunXccUCLzoh9F3rzbus8lP6io7yknaB/AqKyTj9oBY7AXT9r1wnEmO56XNQu11PK1qu2JeCOzkF52784vh+XNBfPTvJYmJy1c7m1Sys0rta2m6F9c3bZV24ZWPaY7DkfwcT6ytXJP44D6NI1k1cOOwmJ8oJfNkrgNBUTUfd8rKu4alKAG0VB59imTVH25ZYzUdxqiiG+tuXJ4ZG8bvreyfk4qTiF5BqdU0/iqGgEkdn2px7UZd656svLGI9qRodSCFhd7pCHw2UfGakGweRG9cW4GEYdDwHnEx+l2g8vc6EQ="

install:
  # Install reviewdog.
  - go get -u github.com/golang/dep/...
  - dep ensure
  - go install ./cmd/reviewdog
  # Install CI tools.
  - go get github.com/haya14busa/goverage
  # Install linters.
  - go get github.com/golang/lint/golint
  - go get github.com/kisielk/errcheck
  - go get honnef.co/go/tools/cmd/gosimple
  - go get honnef.co/go/tools/cmd/staticcheck
  - go get honnef.co/go/tools/cmd/unused

before_script:
  - echo $TRAVIS
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_PULL_REQUEST_SHA
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_SECURE_ENV_VARS
  - curl httpbin.org/ip

script:
  - reviewdog -reporter=github-pr-check
  - go test -v -race $(go list ./... | grep -v "/vendor/")
  - goverage -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - zip -r source.zip . && mkdir dist && mv source.zip dist
  - go get github.com/mitchellh/gox
  - gox -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}" ./cmd/reviewdog/

deploy:
  provider: releases
  api_key:
    secure: "gOJqairdmqDqBeWvwVv6cuUOeX3uIEoufVv6/s37E+AFDth+F5t8aUinV7uaIV/FjNlucFM5T8sY1pkPiTY7ChiUkn9Fvulz9XCPwKqDymlL8i10pQP4GfgdbeVG2k+U42s+MEQBugj73GQTrYTT5UaXv3jHZUcMAbYzJUJU15sdnsqm/1VQShuKq05hDDkJqWUruZiKKMTaq5+SJoZ0YHoACx/0CMnC65+aT/BJSuHJRD6lPIq+bEA+jD1CrZ0Jkxbwxh8nHzX67GRjYpevnNgrpzheC0nKkugIX+ePds8758sQmBsjqfao7CrvEQxeI6fkZHE0vge44dt0iUixaEZaA/YoY7vdhZwkbqPfcVNBCthHee2qkCmosYmn2ipOcnyXLpHYHCp4KDiIz5ny+QNZVxd5qQbXzgDEFQw8D3grNrXEvSTyq+yZB0Ti27tL6gonvjg/ejBwjtzgfvyMZVuZRbnEwBYJDVpZ/W5A0Gr3W1mfDrW1I5/ALh0Y2kd3Erd4XzCnYLupxh1USt8648ONVFaP68ppDeKGNcmrxRIYB8JGe6VQMoxnRWjwN2xf9UNIXy8KWDtbRUlP1R92V3jUmZf2VqFkLdJVWSFs0sHlPEGeaTnk7WZLWMWQpBTJHJbeY9jYme5m4T0a7hCV+kM1WufSaMQCUmm3R0i4dkA="
  file:
    - dist/source.zip
    - dist/reviewdog_darwin_386
    - dist/reviewdog_darwin_amd64
    - dist/reviewdog_freebsd_386
    - dist/reviewdog_freebsd_amd64
    - dist/reviewdog_freebsd_arm
    - dist/reviewdog_linux_386
    - dist/reviewdog_linux_amd64
    - dist/reviewdog_linux_arm
    - dist/reviewdog_netbsd_386
    - dist/reviewdog_netbsd_amd64
    - dist/reviewdog_netbsd_arm
    - dist/reviewdog_openbsd_386
    - dist/reviewdog_openbsd_amd64
    - dist/reviewdog_windows_386.exe
    - dist/reviewdog_windows_amd64.exe
  skip_cleanup: true
  on:
    tags: true
    go: "1.10.x"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/60344004ff53f5ef37c5
    on_success: change
    on_failure: always
    on_start: never
