version: 2.1

executors:
  golang-executor:
    docker:
      - image: cimg/go:1.21.7

jobs:
  lint:
    working_directory: ~/reviewdog
    executor: golang-executor
    steps:
      - checkout
      - run:
          name: System information
          command: 'echo "Golang $(go version)"'
      - run: 'curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $(go env GOPATH)/bin'
      - run: go install golang.org/x/lint/golint@latest
      - run:
          command: |-
            set +o pipefail
            golint ./... | reviewdog -f=golint -name=golint-circleci -reporter=github-pr-review
workflows:
  version: 2
  lint:
    jobs:
      - lint
