version: 2

jobs:
  build:
    working_directory: ~/reviewdog
    docker:
      - image: golang:latest
        environment:
          REVIEWDOG_VERSION: 0.9.9
    steps:
      - checkout
      - run:
          name: System information
          command: |
            echo "Golang $(go version)"
      - run: curl -fSL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o reviewdog && chmod +x ./reviewdog
      - run: go get honnef.co/go/tools/cmd/unused
      - run: unused ./... | ./reviewdog -efm="%f:%l:%c: %m" -name=unused -reporter=github-pr-review

notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/1285d150756c4cbf4795
