name: depup
on:
  schedule:
    - cron:  '14 14 * * *' # Runs at 14:14 UTC every day
  repository_dispatch:
    types: [depup]
  workflow_dispatch:

jobs:
  protoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-depup@v1
        id: depup
        with:
          file: proto/Dockerfile
          version_name: PROTOC_VERSION
          repo: protocolbuffers/protobuf
      - name: Update
        if: {{ steps.depup.latest != steps.depup.current }}
        working-directory: proto/
        run: ./update.sh
      - uses: actions/setup-go@v5
        if: success()
        with:
          go-version-file: "go.mod"
      - name: Build
        if: success()
        run: go build ./...
      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v7
        with:
          title: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          body: |
            Update [${{ steps.depup.outputs.repo }}](https://github.com/${{ steps.depup.outputs.repo }}) to [${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/${{ inputs.tag_prefix }}${{ steps.depup.outputs.latest }})
            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: depup/${{ steps.depup.outputs.repo }}
          base: ${{ github.event.repository.default_branch }}
          labels: ${{ inputs.labels }}

  protoc-gen-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-depup@v1
        id: depup
        with:
          file: proto/Dockerfile
          version_name: PROTOC_GEN_GO_VERSION
          repo: protocolbuffers/protobuf-go
      - name: Update
        if: {{ steps.depup.latest != steps.depup.current }}
        working-directory: proto/
        run: ./update.sh
      - uses: actions/setup-go@v5
        if: success()
        with:
          go-version-file: "go.mod"
      - name: Build
        if: success()
        run: go build ./...
      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v7
        with:
          title: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          body: |
            Update [${{ steps.depup.outputs.repo }}](https://github.com/${{ steps.depup.outputs.repo }}) to [${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/${{ inputs.tag_prefix }}${{ steps.depup.outputs.latest }})
            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: depup/${{ steps.depup.outputs.repo }}
          base: ${{ github.event.repository.default_branch }}
          labels: ${{ inputs.labels }}

  protoc-gen-jsonschema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-depup@v1
        id: depup
        with:
          file: proto/Dockerfile
          version_name: PROTOC_GEN_JSONSCHEMA_VERSION
          repo: chrusty/protoc-gen-jsonschema
      - name: Update
        if: {{ steps.depup.latest != steps.depup.current }}
        working-directory: proto/
        run: ./update.sh
      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v7
        with:
          title: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          body: |
            Update [${{ steps.depup.outputs.repo }}](https://github.com/${{ steps.depup.outputs.repo }}) to [${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/${{ inputs.tag_prefix }}${{ steps.depup.outputs.latest }})
            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: depup/${{ steps.depup.outputs.repo }}
          base: ${{ github.event.repository.default_branch }}
          labels: ${{ inputs.labels }}
