name: depup
on:
  schedule:
    - cron:  '14 14 * * *' # Runs at 14:14 UTC every day
  repository_dispatch:
    types: [depup]
  workflow_dispatch:

jobs:
  protoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: haya14busa/action-depup@94a1aaf4e4923064019214b48a43276218af7ad5 # v1.6.4
        id: depup
        with:
          file: proto/Dockerfile
          version_name: PROTOC_VERSION
          repo: protocolbuffers/protobuf
      - name: Update
        if: ${{ steps.depup.latest != steps.depup.current }}
        working-directory: proto/
        run: ./update.sh
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        if: ${{ steps.depup.latest != steps.depup.current }}
        with:
          go-version-file: "go.mod"
      - name: Build
        if: ${{ steps.depup.latest != steps.depup.current }}
        run: go build ./...
      - name: Create Pull Request
        if: ${{ steps.depup.latest != steps.depup.current }}
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          title: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          body: |
            Update [${{ steps.depup.outputs.repo }}](https://github.com/${{ steps.depup.outputs.repo }}) to [${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/${{ inputs.tag_prefix }}${{ steps.depup.outputs.latest }})
            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: depup/${{ steps.depup.outputs.repo }}
          base: ${{ github.event.repository.default_branch }}
          labels: ${{ inputs.labels }}

  protoc-gen-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: haya14busa/action-depup@94a1aaf4e4923064019214b48a43276218af7ad5 # v1.6.4
        id: depup
        with:
          file: proto/Dockerfile
          version_name: PROTOC_GEN_GO_VERSION
          repo: protocolbuffers/protobuf-go
      - name: Update
        if: ${{ steps.depup.latest != steps.depup.current }}
        working-directory: proto/
        run: ./update.sh
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        if: ${{ steps.depup.latest != steps.depup.current }}
        with:
          go-version-file: "go.mod"
      - name: Build
        if: ${{ steps.depup.latest != steps.depup.current }}
        run: go build ./...
      - name: Create Pull Request
        if: ${{ steps.depup.latest != steps.depup.current }}
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          title: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          body: |
            Update [${{ steps.depup.outputs.repo }}](https://github.com/${{ steps.depup.outputs.repo }}) to [${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/${{ inputs.tag_prefix }}${{ steps.depup.outputs.latest }})
            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: depup/${{ steps.depup.outputs.repo }}
          base: ${{ github.event.repository.default_branch }}
          labels: ${{ inputs.labels }}

  protoc-gen-jsonschema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: haya14busa/action-depup@94a1aaf4e4923064019214b48a43276218af7ad5 # v1.6.4
        id: depup
        with:
          file: proto/Dockerfile
          version_name: PROTOC_GEN_JSONSCHEMA_VERSION
          repo: chrusty/protoc-gen-jsonschema
      - name: Update
        if: ${{ steps.depup.latest != steps.depup.current }}
        working-directory: proto/
        run: ./update.sh
      - name: Create Pull Request
        if: ${{ steps.depup.latest != steps.depup.current }}
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          title: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          body: |
            Update [${{ steps.depup.outputs.repo }}](https://github.com/${{ steps.depup.outputs.repo }}) to [${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/${{ inputs.tag_prefix }}${{ steps.depup.outputs.latest }})
            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: depup/${{ steps.depup.outputs.repo }}
          base: ${{ github.event.repository.default_branch }}
          labels: ${{ inputs.labels }}
